# Generated by Django 5.0.6 on 2024-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_image', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('abilities', models.CharField(max_length=100)),
                ('attacks', models.CharField(max_length=100)),
                ('weaknesses', models.CharField(max_length=100)),
            ],
        ),
    ]
