# Generated by Django 5.0.6 on 2024-05-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='card',
        ),
        migrations.AddField(
            model_name='listing',
            name='collection',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
    ]
